### ISSUE TITLE
Add documentation for libraries creation

### ISSUE THREAD

**Issue by pablo-araya-hpe** [HPENetworking/cookiecutter_topology_lib#1]
This repo doesn't have any documentation. 
As I've seen in different communication channels the team in general requires a "how to" guide for libraries creation; which at least explains:

1- How to add new vtysh configuration calls
2- How to add new vtysh show calls
3- How to add new communication libraries (REST for example)

**Comment by ocelotl** [comment]
Those previous points are wrong.

There _is_ documentation in this repo, the README file explains how to use it.
This is a _cookiecutter_ repo, whose purpose is to create templated repos for libraries, not the place where documentation for specific libraries (like vtysh) should be (also, the vtysh documentation clearly explains how to add configuration and show calls, just run tox -e doc and read the HTML generated documentation, please).
I have just added one more line in the README file that shows where the library functions would go, the `library.py` file already shows that, but it won't hurt.
Finally, is _impossible_ to explain how to create any new communication library since every one has a specific architecture tailored to the nature of the commands that form the library (the differences between the vtysh and the ping library are good examples of this), so the only possible documentation to add here is where the library functions are to be placed.
